### ISSUE TITLE
Solares System 20170915-1

### ISSUE THREAD

**Issue by tinagiesler** [tinagiesler/Gattland#13]

**Comment by tinagiesler** [comment]
Bitte die fehlenden Namen und Orte ergänzen!

**Comment by Dembelo-Jessica** [comment]
Zu welcher Zeit spielt der Knoten und wo?

**Comment by tinagiesler** [comment]
Ist das relevant?

**Comment by Dembelo-Jessica** [comment]
Das ist relevant wegen der Namensauswahl. Und um zu wissen, wo schon besiedelt ist. Ich hab jetzt mithilfe der Geschichtskarten improvisiert.

**Comment by Dembelo-Jessica** [comment]
Ich bin verwirrt. In welchem Punkt des WF befinden wir uns gerade?
Aber egal. Das Problem mit dem Ende ist, dass die Geschichte keinen richtigen Höhepunkt hat. Du sagtest was von erzählerischen Rahmen, der kommt hier aber nicht vor.

**Comment by tinagiesler** [comment]
Ich zerschieße den WF gerade. Aber da der Text eh nicht in diesem entstanden ist, ist das wohl notwendig.

**Comment by tinagiesler** [comment]
Ist ins Issue #41 eingegangen und in den entsprechenden Meilenstein.
