### ISSUE TITLE
Namenskonzept für Aleese aufstellen

### ISSUE THREAD

**Issue by tinagiesler** [tinagiesler/Gattland#37]
Aleese hat verschiedene Stände, das muss im Namenskonzept abgebildet werden. Es gibt sowohl Bürgerliche, wie einen Adel und eine gewisse Mischform. Den Adel würde ich gerne mit langen Namensketten abbilden. Weil man dem Kind die Ruhmreiche Vergangenheit der Familie mitgeben will. Die Adeligen werden also mehrere Vornamen und vielleicht sogar mehrere Nachnamen haben, nach der Form FAMILIE von ORT oder sowas.

Die Bürgerlichen werden da eher sparsamer sein.

**Comment by Dembelo-Jessica** [comment]
erledigt
