### ISSUE TITLE
Über Nichtlineares Lesen 20170918-1

### ISSUE THREAD

**Issue by tinagiesler** [tinagiesler/Gattland#6]
Gattland/Lesecluster/Dembelo/20170918-1.odt 

Bitte zu diesem Text ein erstes Feedback

**Comment by Dembelo-Jessica** [comment]
Bitte melden, wenn der Upload nicht funktioniert hat.

**Comment by tinagiesler** [comment]
weiß gerade nicht woran ich das fest machen soll. Ein Update ist da, aber er hatte 0 Änderungen. Vielleicht sollten wir tatsächlich unser Kürzel unter den Text setzen, wenn wir ihn geändert haben, bis wir die Technik richtig im Griff haben.

**Comment by Dembelo-Jessica** [comment]
Dann machen wir das lieber.
